### ISSUE TITLE
Feature Request: implement <gather> outgoing calls

### ISSUE THREAD

**Issue by whmoorejr** [FlyingDiver/Indigo-Twilio#1]
This would combine an autodialer and a touch tone controller.  Add an Action option, "Call with Gather."  

Configure Call with Gather:
Call To: XXX-XXX-XXXX
Message: bla bla bla, press one for bla, press 2 for bla, press 3 for bla, etc.
1 : Select Action Group to execute
2: Select Action Group to execute
3: Select Action Group to execute
...
9: Select Action Group to execute

This would then generate the script to twillio to generate a call that will request information.  I think you can use the <gather> command to execute a HTTP Put command which could in turn fire off an indigo action group.

**Comment by FlyingDiver** [comment]
Not a simple addition.  Requires setting up an Indigo Web Server component in addition to the plugin changes.  User setup would require extra steps as is done for immediate notifications: https://github.com/FlyingDiver/Indigo-Twilio/wiki/Immediate-Notifications

**Comment by whmoorejr** [comment]
I didn't know it had to use a web server component to operate.  I though you could directly command a variable or device via HTML:
http://127.0.0.1:8176/variables/twilio_ping?_method=put&value=true
or 
http://127.0.0.1:8176/actions/twilio_press1?_method=execute

I guess that does make my request a bit more complex.  Sorry about that.  And honestly, this is a feature that I probably wouldn't use.  My plan is to only use the calls for critical notifications (house alarm, fire, etc.) which doesn't need options to gather.

**Comment by FlyingDiver** [comment]
It's not doing the Indigo actions that's the issue.  It's Twilio telling Indigo what buttons you pressed.  Here's the data flow:

1. Twilio plugin sends a request to the Twilio servers via http.

2. Twilio server calls the specified number and gathers the response.

3. Twilio server has to make an http request back to Indigo with the response data.

4. Indigo or some plugin does something with that data (sets variables, calls action group, something).

So it's step 3 that's the tricky part.  Also just the configuration of the Twilio logic on step 2, which is complicated to code but not difficult to execute.

I'm also concerned about the security of step # 3.  How to prevent spoofing.

I think this would be useful addition if I can come up with a straightforward way for the user to set it up.

**Comment by whmoorejr** [comment]
I would think the security of this method would be greater than initiating an action based on a received text.  In this case, Indio (via plugin) has to initiate the communication including the ability to listen for the response.  If there is a timer on this (5min +/-), then indigo will only process a response received within 5 minutes of initiating an action to place the gather call.

**Comment by FlyingDiver** [comment]
There's a number of security issues to address.  If I was to implement this, I'd implement an access token that gets passed from Indigo to Twilio as part of initiating the outbound call, which is also returned in the web callback.

**Comment by FlyingDiver** [comment]
This is now enabled (sort of) using the Twilio Studio Flow API.  Instructions will be in the Wiki as soon as I can write them up.  Requires the current pre-release of the Twilio plugin and pre-release of the HTTPd plugin.

**Comment by whmoorejr** [comment]
I didn’t think you would touch this till after your Africa Trip.  Hakuna Matata!

**Comment by FlyingDiver** [comment]
Jambo!  Have you tried doing anything with the sample flow I posted?

**Comment by whmoorejr** [comment]
I'm running into a couple snags.
Twilio Plugin: v7.2.0
HTTPd Plugin: v1.2.0

Step 13:  Still messing with a ddns account.  I had a free one I never really used... probably because it expires every 30 days... so I might need a more permanent solution for that.

Step 16?: after updating the plugin, I don't see the "Place Flow Request" action.

**Comment by FlyingDiver** [comment]
Place Flow Request is a Twilio Action.  
<img width="1164" alt="screen shot 2018-06-03 at 12 13 49 pm" src="https://user-images.githubusercontent.com/72976/40888603-9cf4df48-6727-11e8-9ae3-e19f7c7cfd70.png">

**Comment by whmoorejr** [comment]
Weird.  I'm running v7.2.0... that is the correct one?  I'm not getting that action option.... Just the original 5 options.  Tried disable/enable the plugin, restart Indigo, even re-booted the server computer a couple times.

**Comment by FlyingDiver** [comment]
As I mentioned in an earlier post, you need to be running the latest pre-release (beta) version of the plugins.  I think it was Beta 2.  Beta 3 is now available.

https://github.com/FlyingDiver/Indigo-Twilio/releases
https://github.com/FlyingDiver/Indigo-HTTPd/releases

**Comment by whmoorejr** [comment]
Success!
My Indigo wasn't recognizing the differences between the betas.... so it wasn't upgrading... just re-enabling Beta1 over and over.  Once I removed the plugin from the plugin folder, I was able to re-install beta 3.  

Let me know if this all looks correct....
Under the HTTPd variable folder, I now have "http_twilio_option" and "http_twil_auth".  I see my phone response populated the option variable... not sure what to do with eh "auth" variable".... but now I can set up triggers and I'm good to go.... right?

**Comment by FlyingDiver** [comment]
The auth field is there for security checking.  You should compare the value in that variable to the last_auth state of the Twilio device.  If they don't match, then the option variable was not set by a valid flow request. At least, that's the intent.  Not sure how much testing that got.

**Comment by whmoorejr** [comment]
Got it.  How often does that Auth code change?  Three tests so far, new code each time... wrote a quick control page to display the Twilio Auth code next to the "http_twil_auth" and they match up when I run the flow.  I guess that could be put in as a condition in a trigger "Device state = variable" as a form of authentication?  Either way... this is pretty bad-ass.  My head is already spinning thinking of things to do with this and where to implement it.  I greatly appreciate all your work on this and for dealing with me.

**Comment by FlyingDiver** [comment]
It's a random number string generated for each flow request.  Passed to the Twilio server along with the request.  So I think it's a pretty good way to verify that it's a legit callback.  But I'm not a security expert, so I can't guarantee it can't be hacked.

And yes, adding it as a conditional was the intent.

**Comment by whmoorejr** [comment]
Well, bravo... this is pretty sweet.  I'm not well versed in IT security either, but I do see several layers here that make it pretty secure.  On top of using the auth code as a condition.... I would only enable the trigger for a brief time when the flow is executed.  Once that trigger fires, I would re-populate the variables with a placeholder "null", "0000", etc.  I guess you could set up a second trigger that is enabled in reverse (disabled when the primary trigger is enabled... and visa-versa) that watches those variables for any change and sends you a text/pushover/growl etc.... (so that trigger would fire if there was an unauthorized change to those variables)
