### ISSUE TITLE
New Error, probably on my side

### ISSUE THREAD

**Issue by mundmc** [FlyingDiver/Indigo-Twilio#11]
Aug 2, 2022 at 4:33:54 PM
Action Group TWILIO_findphone_dan
Twilio Error Error in plugin execution ExecuteAction:

File "plugin.py", line 316, in voiceMessageAction
File "plugin.py", line 322, in voiceMessage
type: module 'urllib' has no attribute 'quote'

I am only getting this when I try to send a voice call from Indigo; though I highly suspect it's my fault on the Twilio side. Enjoy your vacation!

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-Twilio/releases/tag/2022.0.2
