### ISSUE TITLE
Missing Actions in Twilio Plugin

### ISSUE THREAD

**Issue by mjcreamer** [FlyingDiver/Indigo-Twilio#12]
After upgrading to the latest version of the Twilio plugin, I only see these options under Twilio Actions:

- Place Flow Request
- Check for Messages

I no longer see the options to Place a Call or Send SMS.

I completely removed and reinstalled the plugin but still do not see the missing options.

Am I missing a step?

Thanks,
Michael

**Comment by FlyingDiver** [comment]
Show logs.

**Comment by mjcreamer** [comment]
Aug 22, 2022 at 12:56:01 PM
   Twilio Debug                    Called deviceStopComm(self, device): Twilio 804-655-4968 (1777205809)
   Twilio Debug                    Called deviceStartComm(self, device): Twilio 804-655-4968 (1777205809)
   Twilio Debug                    Twilio 804-655-4968: Device Current Version = 2
   Twilio Debug                    Twilio 804-655-4968: Device Version is up to date
   Reloading plugin "Twilio 2022.0.1" using API v3.0
   Stopping plugin "Twilio 2022.0.1" (pid 4562)
   Twilio Debug                    stop_concurrent_thread called
   Twilio Debug                    stop_concurrent_thread called
   Twilio Debug                    Called deviceStopComm(self, device): Michael 804-677-7370 (183271540)
   Twilio Debug                    Called deviceStopComm(self, device): Twilio 804-655-4968 (1777205809)
   Twilio                          Shutting down Twilio
   Stopped plugin "Twilio 2022.0.1"
   Starting plugin "Twilio 2022.0.1" (pid 4580)
   Twilio Debug                    logLevel = 10
   Twilio Debug                    pollFrequency = 0.0
   Twilio Debug                    Twilio API Check response = HTTP 200 <?xml version='1.0' encoding='UTF-8'?>
<TwilioResponse><Versions><Versions><Version><Name>2010-04-01</Name><Uri>/2010-04-01</Uri><SubresourceUris><Accounts>/2010-04-01/Accounts</Accounts></SubresourceUris></Version></Versions></Versions></TwilioResponse>
   Started plugin "Twilio 2022.0.1"
   Twilio                          Starting Twilio
   Twilio Debug                    Called deviceStartComm(self, device): Michael 804-677-7370 (183271540)
   Twilio Debug                    Michael 804-677-7370: Device Current Version = 2
   Twilio Debug                    Michael 804-677-7370: Device Version is up to date
   Twilio Debug                    Called deviceStartComm(self, device): Twilio 804-655-4968 (1777205809)
   Twilio Debug                    Twilio 804-655-4968: Device Current Version = 2
   Twilio Debug                    Twilio 804-655-4968: Device Version is up to date

**Comment by mjcreamer** [comment]
Nevermind.  I see the missing Actions under the Notification Actions menu.  Thanks.

**Comment by FlyingDiver** [comment]
Oh, yeah, those are actually notifications, while the others are not.
